name: Update Lotus Version

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Get latest Lotus version
        id: get-version
        run: |
          LATEST_VERSION=$(node scripts/get-latest-lotus-version.js)
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV

      - name: Run update script
        run: node scripts/update-versions.js ${{ env.LATEST_VERSION }}
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Chore: update Lotus version references to ${{ env.LATEST_VERSION }}'
          title: 'Chore: update Lotus version references to ${{ env.LATEST_VERSION }}'
          body: |
            Automated PR to update Lotus version references to ${{ env.LATEST_VERSION }}
            
            This PR was automatically generated by GitHub Actions.
          branch: update-lotus-version
          base: main
          delete-branch: true